mkdir build
cd build
cmake ^
    "%CMAKE_ARGS%" ^
    -GNinja ^
    -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON ^
    -DCMAKE_CXX_STANDARD=20 ^
    -DCMAKE_BUILD_TYPE=RELEASE ^
    -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -DCMAKE_INSTALL_LIBDIR="%LIBRARY_LIB%" ^
    -DCMAKE_INSTALL_INCLUDEDIR="%LIBRARY_INC%" ^
    -DCMAKE_INSTALL_BINDIR="%LIBRARY_BIN%" ^
    -DCMAKE_INSTALL_DATADIR="%LIBRARY_PREFIX%" ^
    -DSPICEQL_BUILD_DOCS=OFF ^
    -DSPICEQL_BUILD_TESTS=OFF ^
    -DPython3_EXECUTABLE=$PYTHON ^
    ..

cmake --build . --config RELEASE
cmake --install . --config RELEASE
if errorlevel 1 exit 1
