{% set name = "spiceql" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: .
    url: https://github.com/DOI-USGS/SpiceQL/archive/refs/tags/{{ version }}.tar.gz
    sha256: b76b2c66131e96eb0a80718717b2447c53a33a42e73dcd568c508c9e70474d2b

  # submodules
  - folder: submodules/json
    url: https://github.com/nlohmann/json/archive/fac07e22c5d7dd0423ccf31c02db5603d27e6556.zip
    sha256: 191543fd27175d57bd6d2f56cb4f63e424cb56379acb6f367bad3ce34a2bb9c3
  - folder: submodules/gularkfilesystem
    url: https://github.com/gulrak/filesystem/archive/fcea331ebb8273581cef3e91a131e3d7877f7dfd.zip
    sha256: c2775dccc5d8f6d8654bd4b1ef2302b26b8cb75f140640dc2328a58d643f3818
  - folder: submodules/BTree
    url: https://github.com/frozenca/BTree/archive/924230033c9696758958e7ea6877c21da24ea2da.zip
    sha256: 02861d263273c02b91ecafc652608d1004bbd48f75e395ccf7c2d07ed502c1ed



build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                               
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make
    - swig
    - cmake-no-system >=3.14

  host:
    - setuptools
    - cpp-filesystem
    - pip
    - cereal
    - highfive
    - cspice
    - hdf5
    - fmt >9,<10
    - spdlog =1.12
    - openssl >=3.5,<4
    - python
    - libcurl >=8.14.1,<9
  run:
    - python
    - cspice
    - hdf5
    - {{ pin_compatible('libcurl', max_pin='x.x') }}
    - {{ pin_compatible('openssl', max_pin='x.x') }}


test:
  imports:
    - pyspiceql
  commands:
    - test -e $PREFIX/lib/libSpiceQL${SHLIB_EXT}  # [unix]
    - test -e $PREFIX/include/SpiceQL/config.h  # [unix]
    - if not exist %LIBRARY_BIN%\SpiceQL.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\SpiceQL.lib exit 1  # [win]

about:
  home: https://code.usgs.gov/astrogeology/spiceql
  summary: "This Library provides a C++ interface querying, reading and writing Naif SPICE kernels."
  license: CC0-1.0
  license_file:
    - LICENSE.md
    - submodules/json/LICENSE.MIT
    - submodules/gularkfilesystem/LICENSE
    - submodules/BTree/LICENSE.md
  doc_url: https://astrogeology.usgs.gov/docs/manuals/spiceql
  dev_url: https://code.usgs.gov/astrogeology/spiceql

extra:
  recipe-maintainers:
    - acpaquette
    - Kelvinrr
    - chkim-usgs
