{% set name = "spiceql" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: .
    url: https://github.com/DOI-USGS/SpiceQL/archive/refs/tags/{{ version }}.tar.gz
    sha256: eb81a2fde42ad8c9e78d2a89efbf1a4bc9cbb5c121ecb0c9d586b3e6ede30b84

  # submodules
  - folder: submodules/json
    url: https://github.com/nlohmann/json/archive/fac07e22c5d7dd0423ccf31c02db5603d27e6556.zip
    sha256: 191543fd27175d57bd6d2f56cb4f63e424cb56379acb6f367bad3ce34a2bb9c3
  - folder: submodules/gularkfilesystem
    url: https://github.com/gulrak/filesystem/archive/fcea331ebb8273581cef3e91a131e3d7877f7dfd.zip
    sha256: c2775dccc5d8f6d8654bd4b1ef2302b26b8cb75f140640dc2328a58d643f3818
  - folder: submodules/BTree
    url: https://github.com/frozenca/BTree/archive/924230033c9696758958e7ea6877c21da24ea2da.zip
    sha256: 02861d263273c02b91ecafc652608d1004bbd48f75e395ccf7c2d07ed502c1ed

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.14
    - make
    - swig

  host:
    - python
    - setuptools
    - cpp-filesystem
    - fmt >9,<10
    - pip
    - cereal
    - highfive
    - cspice
    - spdlog =1.13
  run:
    - cspice
    - python
    - hdf5

test:
  imports:
    - pyspiceql
  commands:
    - test -e $PREFIX/lib/libSpiceQL${SHLIB_EXT}  # [unix]
    - test -e $PREFIX/include/SpiceQL/config.h  # [unix]
    - if not exist %LIBRARY_BIN%\SpiceQL.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\SpiceQL.lib exit 1  # [win]

about:
  home: https://code.usgs.gov/astrogeology/spiceql
  summary: "This Library provides a C++ interface querying, reading and writing Naif SPICE kernels."
  license: CC0-1.0
  license_file:
    - LICENSE.md
    - submodules/json/LICENSE.MIT
    - submodules/gularkfilesystem/LICENSE
    - submodules/BTree/LICENSE.md
  doc_url: https://sugar-spice.readthedocs.io/en/latest/#docs
  dev_url: https://code.usgs.gov/astrogeology/spiceql

extra:
  recipe-maintainers:
    - Kelvinrr
    - chkim-usgs
