github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
  pkg_format: '2'
conda_forge_output_validation: true
provider:
    linux_aarch64: emulated
    osx: azure
    win: azure
build_platform:
  osx_arm64: osx_64
test: native_and_emulated
